"""Genera contactos_catalan_ronda2.xlsx con gestorías reales de Girona, Tarragona,
Mataró, Reus, Manresa y Granollers (búsqueda julio 2026). Excluye duplicados de email
ya presentes en tandas anteriores."""
from openpyxl import Workbook

# emails ya usados en tandas anteriores (para no escribir dos veces al mismo buzón)
YA_ENVIADOS = {"gestoria@gestoriagilsellares.com"}

# (empresa, ciudad, email_o_None, fuente_o_None)
GESTORIAS = [
    ("Gestoria de la Guardia", "Reus", None, "https://www.gestoriadelaguardia.com/"),
    ("Assessors Empresarials Gestimax S.L.", "Reus", "informacion@gestimax.net", "https://www.assessoriesreus.com/"),
    ("MBC Assessors S.L.", "Reus", "info@mbcassessors.com", "https://www.mbcassessors.com/"),
    ("Centre Gestor Baix Camp", "Reus", "info@gestoriabaixcamp.cat", "https://www.gestoriabaixcamp.es/"),
    ("Estivill Assessors (ETL Global)", "Reus", "estivill@estivill.com", "https://www.estivill.com/"),
    ("Gascón Gestión Empresarial", "Reus", None, "http://www.gascongestion.com/"),
    ("Dalmau - Mines Serveis Administratius", "Reus", "dalmaumines@gmail.com", "https://dalmaumines.com/"),
    ("Serveis Administratius Baix Camp", "Reus", "info@serveisbaixcamp.es", "http://serveisbaixcamp.es/"),
    ("Dipor Assessorament", "Reus", "javier@dipor.net", "http://dipor.net/"),
    ("Xavier Masdeu Assessoria", "Reus", "info@masdeuasesoria.com", "http://www.masdeuasesoria.com/"),
    ("Afico - Assessoria Integral d'Empreses", "Reus", "fiscal@aficosl.es", "https://aficosl.com/"),
    ("Òptima Assessors", "Reus", "info@optimagrup.com", "http://www.optimagrup.com/"),
    ("Assessoria Ienode", "Reus", "info@ienode.com", "https://ienode.com/"),
    ("Mitt Assessors", "Reus", "info@mitt.es", "http://mitt.es/"),
    ("Assessoria Casado", "Reus", "info@assessoriacasado.com", "https://assessoriacasado.com/"),
    ("Prodempresa Reus", "Reus", "gerencia@prodempresa.com", "https://prodempresa.com/"),
    ("SA Consulting (Sabater Assessors)", "Reus", "info@sareus.com", "https://sareus.com/"),
    ("Casals i Torres Assessoria Empresarial", "Reus", "fiscal@ajca.es", "http://www.ajca.es/"),
    ("Gestoría Llurba Garzón S.L.", "Reus", "llurbagarzon@terra.es", "https://llurbagarzon.com/"),
    ("Roig Consulting Assessors", "Reus", "pere@roig-consulting.cat", "http://roig-consulting.cat/"),
    ("Gabinet Assessors", "Reus", "gabinet@acogest.net", "http://www.acogest.net/"),
    ("Arcano Assessors", "Reus", None, "https://www.arcanoassessors.com/"),
    ("Prats Canela Assessors Laborals", "Reus", None, "https://www.gestorias24.com/ubicaciones/reus"),

    ("ConsultIn (Consultores Integrales)", "Manresa", "info@consultin.es", "https://consultin.es/"),
    ("Gestoria Hurtado", "Manresa", "hurtado@sanfeliu.com", "https://gestoriahurtado.cat/"),
    ("Talenom Asesoría Manresa", "Manresa", None, "https://talenom.com/es-es/oficinas/asesoria-manresa/"),
    ("Semar Consultora", "Manresa", None, "https://www.semarconsultora.com/es/"),
    ("Gestoria Roset", "Manresa", "manresa@roset.info", "http://www.rosetconsultors.com/"),
    ("Gestoria Casasayas", "Manresa", "gestoria@casasayas.eu", "http://www.gestoriacasasayas.es/"),
    ("Arfe Arderiu Consultors", "Manresa", "arfe@arfe.es", "http://www.arfeconsultors.com/"),
    ("Asesoría Minorisa", "Manresa", "info@asesoriaminorisa.com", "http://www.asesoriaminorisa.com/"),
    ("Tràmit Pinos Assessors", "Manresa", "info@tramitpinos.com", "http://www.tramitpinos.com/"),
    ("Assessoria-Gestoria Puigdellívol S.C.P.", "Manresa", "geaspuig@ofisip.es", "http://ofisip.es/"),
    ("Sensus Consultoria", "Manresa", None, "http://www.sensusconsultoria.com/"),
    ("Gestoria Plinio Gómez S.L.", "Manresa", "gestoriapliniogomez@gestors.net", "http://gestoriapliniogomez.com/"),
    ("ATI Assessors", "Manresa", None, "https://www.atiassessors.com/"),
    ("Gestoria Administrativa F. Pons Boixader i Associats S.L.", "Manresa", None, "http://ponsboixader.com/"),
    ("Business Action S.L.", "Manresa", "info@businessaction.net", "http://www.businessaction.net/"),
    ("Assessoria Integral Cubo Pons", "Manresa", "info@cubopons.com", "https://www.cubopons.com/"),
    ("Gestoria Nostramits", "Manresa", "gestor3956@outlook.es", "https://gestorianostramits.com/"),
    ("Gil Sellarès Gestoria (Manresa)", "Manresa", "gestoria@gestoriagilsellares.com", "https://www.gestoriagilsellares.com/"),
    ("Gestoria Tributaria M.V.", "Manresa", None, "http://www.gestoriatributariamv.com/"),
    ("Gesbages - Planificació i Organització Empresarial", "Manresa", "info@gesbages.com", "http://www.gesbages.com/"),
    ("Manalbens Economistes S.L.", "Manresa", None, "https://www.gestorias24.com/ubicaciones/manresa"),
    ("Gestoría Administrativa Ángel Bra Sánchez S.L.", "Manresa", None, "https://www.absgestors.com/gestoria-en-manresa"),
    ("ATF Assessors i Consultors", "Manresa", "info@atfassessors.com", "https://atfassessors.com/es/"),

    ("NC Granollers", "Granollers", "info@ncgranollers.com", "https://www.ncgranollers.com/"),
    ("GC Assessors Comptables", "Granollers", None, "https://gestiocomptable.com/"),
    ("Prat Mora", "Granollers", "pratmora@pratmora.com", "https://pratmora.com/es/asesoria-gestoria-granollers/"),
    ("Assessoria Coll Gestoria S.L.", "Granollers", None, "https://www.gestoriacoll.es/"),
    ("NN Laboral Congost", "Granollers", None, "https://www.nnlaboralcongost.com/"),
    ("Bufet Estalella", "Granollers", "bufetestalella@bufetestalella.com", "https://www.bufetestalella.com/fiscal-contable/"),
    ("Vila i Lancis", "Granollers", "info@vilalancis.com", "https://vilalancis.com/asesoria-en-granollers/"),
    ("Gestoria Dominguez", "Granollers", "info@gestoriadominguez.com", "https://gestoriadominguez.com/"),
    ("VYA Asesores Digitales S.L.", "Granollers", "admin@vya.es", "https://vya.es/"),
    ("Mitalo Vallès", "Granollers", "info@mitalovalles.com", "http://www.mitalovalles.com/"),
    ("Àgora S.A. d'Assessorament i Serveis", "Granollers", None, "http://www.agora-sa.com/"),
    ("Guiteras Assessors", "Granollers", "gra@guiteras.com", "https://www.guiteras.com/"),
    ("Miró Assessors", "Granollers", "info@miroassessors.com", "https://miroassessors.com/es/bienvenidos/"),
    ("AGC Assessors (oficina Granollers)", "Granollers", "granollers@agc.cat", "https://www.agc.cat/oficina-granollers-1"),
    ("AIG Assessoria", "Granollers", None, "https://www.aig.cat/serveis/"),
    ("Gestoria y Asesoria del Vallès", "Granollers", "info@gestoriayasesoria.com", "https://www.gestoriayasesoria.com/"),
    ("Serra i Aymerich", "Granollers", None, "https://www.gestorias.es/barcelona/granollers/gestoria-serra-i-aymerich-5312"),
    ("Àrea de Gestió Granollers S.L.", "Granollers", None, "https://www.gestorias.es/barcelona/granollers/area-de-gestio-granollers-6495"),
    ("Gesmira (Asesoría-Gestoría)", "Granollers", None, "https://www.paginasamarillas.es/a/gestorias/barcelona/granollers/"),
    ("Gestoria Camprubí Aragonès", "Granollers", None, "https://www.gestorias.es/barcelona/granollers/gestoria-camprubi-2632"),
    ("Assessors Granogest S.L.P.", "Granollers", "mreche@granogest.com", "https://www.gestorias.es/barcelona/granollers/granogest-487"),
    ("Marinamarc Asesores Empresariales S.L.", "Granollers", "cristoballopezblancas@economistes.com", "https://www.gestorias.es/barcelona/granollers/marinamarc-asesores-empresariales-18619"),
    ("Punt Vermell Gestors Administratius", "Granollers", "gestoria@puntvermell.es", "https://puntvermell.com/es/inicio/"),

    ("Gestoria Roig", "Girona", "gestoria@gestoriaroig.com", "https://www.gestoriaroig.net/contacto"),
    ("Girotràmits Gestor", "Girona", "eva@girotramits.com", "https://www.cylex.es/girona/girotr%C3%A0mits-gestor-13268840.html"),
    ("Somer Gestoria Assessoria", "Girona", "somer@gestoriasomer.cat", "https://www.gestoriasomer.cat/es/"),
    ("Gestoria Reverendo", "Girona", "info@gestoriareverendo.com", "https://www.gestoriareverendo.com/"),
    ("Gestoria Pou", "Girona", "gestoriapou@gestoriapou.cat", "https://www.gestoriapou.cat/es/contacte-espanol/"),
    ("VeraGestions Assessoria", "Girona", "info@veragestions.com", "https://veragestions.com/"),
    ("Gestoria Izquierdo", "Girona", "info@gestoriaizquierdo.com", "https://www.gestoriaizquierdo.com/"),
    ("Bigas Assessoria i Gestió", "Girona", "info@bigasassessoria.com", "https://www.bigasassessoria.cat/Espanol/index.html"),
    ("Ribas Alvarez Assessors i Consultors", "Girona", "assessoria@ribasalvarez.cat", "https://ribasalvarez.cat/"),
    ("Gefgirona", "Girona", "info@gefgirona.com", "https://gefgirona.com/contacte/"),
    ("Ace de Las Heras", "Girona", None, "https://www.gestorias.es/girona/girona/ace-de-las-heras-sl-16896"),
    ("Gestoria de Pimes", "Girona", "info@gestoriadepimes.com", "https://gestoriadepimes.com/"),
    ("Grup Simon Assessors", "Girona", "info@grupsimon.com", "https://www.paginasamarillas.es/f/girona/grup-simon-assessors_142511351_000000002.html"),
    ("Gestoria Lardon Rusiñol", "Girona", "info@gestoriarusinol.com", "https://gestoriarusinol.com/"),
    ("Gabinet Oliva S.L.", "Girona", "aoliva@gabinet-oliva.com", "https://empresite.eleconomista.es/GABINET-OLIVA.html"),
    ("Anper Consultors", "Girona", "info@anperconsultors.com", "https://anperconsultors.com/contacte-anperconsultors-girona-anperconsultors/"),
    ("Collell i Frigola SLP", "Girona", "info@collellifrigola.com", "https://empresite.eleconomista.es/COLLELL-FRIGOLA-SLP.html"),
    ("IDES Economistes i Advocats", "Girona", "ides@idesassessors.com", "https://www.idesassessors.com/es/contacto.html"),
    ("Comgest Economistes S.L.", "Girona", "info@comgesteconomistes.com", "https://comgesteconomistes.com/"),
    ("Gestoria Guardiola", "Girona", "info@guardiola.cat", "https://www.guardiola.cat/es/contacto.aspx"),
    ("Assessoria Girona", "Girona", "fiscal@assessoriagirona.cat", "https://empresite.eleconomista.es/ASSESSORIA-GIRONA.html"),
    ("Gestoria Equalink Central de Negocis", "Girona", "gestoria@equalink.es", "https://empresite.eleconomista.es/GESTORIA-EQUALINK-CENTRAL-NEGOCIS.html"),

    ("Asesoría Pérez - Tarracogest", "Tarragona", "info@tarracogest.com", "https://www.tarracogest.com/contacto/"),
    ("Sugrañes Assessors", "Tarragona", "info@sugranyes.com", "https://www.sugranyes.com/contacte/"),
    ("Cadiach Assessors", "Tarragona", "gestoria@cadiach.com", "https://www.cadiach.com/"),
    ("Gestoria Belén Garcia S.L.P.", "Tarragona", "info@gestoriabelen.com", "https://gestoriabelen.com/"),
    ("Gesser Gestió Fiscal i Comptable", "Tarragona", "jm@gesser.info", "https://empresite.eleconomista.es/GESSER-GESTIO-FISCAL-COMPTABLE.html"),
    ("M&T Assessors Tarragona", "Tarragona", "meitel@mtassessors.com", "http://www.mtassessors.com/"),
    ("Ogima Assessors", "Tarragona", "info@ogima.es", "https://www.ogima.cat/"),
    ("Gestalia Assessors", "Tarragona", "info@gestaliagrup.com", "https://www.gestaliagrup.com/"),
    ("Tributalia Abogados Tributarios S.L.", "Tarragona", "info@tributaliabogados.com", "http://www.tributaliaabogados.com/"),
    ("Mezquida Consultors Associats", "Tarragona", "info@mezquidaconsultors.com", "https://www.mezquidaconsultors.com/"),
    ("Asein Assessors Tarragona", "Tarragona", "asein@aseintarragona.com", "https://aseintarragona.com/"),
    ("Gestoria Administrativa Boronat (Tarragona)", "Tarragona", "gestorboronat@gestores.net", "https://www.gestoriaboronat.es/"),
    ("AZV Consulting Tarragona", "Tarragona", "tarragona@azvconsulting.com", "https://azvconsulting.com/delegacion-tarragona/"),
    ("Asesoria Tarragona S.L.", "Tarragona", "assandra@tiservinet.es", "https://empresite.eleconomista.es/ASESORIA-TARRAGONA.html"),
    ("Gestoria Riola", "Tarragona", "gesriola@gestores.net", "https://gestoriariola.com/"),
    ("Gadin", "Tarragona", "info@gadin.cat", "https://gadin.cat/en/"),
    ("Gestoria Font", "Tarragona", None, "https://fontgestoria.com/"),
    ("Campdepadros Gestoria", "Tarragona", None, "http://www.campdepadros.cat/contacte.php"),
    ("Corporació Raif S.L.", "Tarragona", None, "https://www.gestorias.es/tarragona/43004"),
    ("Ocaia Assessors S.L.", "Tarragona", None, "https://empresite.eleconomista.es/OCAIA-ASSESSORS.html"),
    ("Asde Assessors 2002", "Tarragona", None, "https://www.asdeonline.com/"),
    ("Vives i Roig S.L.", "Tarragona", None, "https://www.empresia.es/empresa/vives-i-roig/"),

    ("Assessoria Buch", "Mataró", "buch@assessoriabuch.com", "https://assessoriabuch.com/es/contacta/"),
    ("Maresme Abogados y Gestores", "Mataró", "maresmeabogados@gmail.com", "https://www.abogadosygestoresmaresme.com/contacto"),
    ("Gestomart P. Martínez Assessors", "Mataró", "gestomart@gestores.net", "https://gestomart.cat/contacto/"),
    ("Gestoria Barceló S.L.", "Mataró", "info@gestoriabarcelo.com", "https://gestoriabarcelo.com/es/contacto/"),
    ("GAM Gestoria Administrativa Maresme", "Mataró", "info@gestoriamaresme.com", "https://gestoriamaresme.com/"),
    ("Gestoria Lladó", "Mataró", "gestoriallado@gestorialladomataro.es", "https://www.gestoriallado.es/"),
    ("Asesoría Goti S.L.P.", "Mataró", "administracion@asesoriagoti.com", "https://asesoriagoti.com/contacto/"),
    ("Easygest.es", "Mataró", "info@easygest.es", "https://www.paginasamarillas.es/f/mataro/easygest-es-_230169948_000000001.html"),
    ("P&S Assessors Maringles S.L.", "Mataró", "info@maringles.com", "https://maringles.com/"),
    ("BL Economistes", "Mataró", "info@bleconomistes.com", "https://bleconomistes.cat/"),
    ("Ametller Economistes S.L.", "Mataró", "roser@ametller-economistes.com", "https://empresite.eleconomista.es/AMETLLER-ECONOMISTES-SLP.html"),
    ("Iluro Gestió S.C.P.", "Mataró", "administracion@asesoria-iluro.com", "https://www.asesoria-iluro.com/"),
    ("Rodon i Vergés Associats S.L.", "Mataró", "info@rodonverges.com", "https://rodonverges.com/"),
    ("Asesoria Garó", "Mataró", "info@assessoriagaro.com", "https://www.assessoriagaro.com/contactar/"),
    ("Cecassa Assessors", "Mataró", "cecassa@cecassa.com", "https://cecassa.com/contacto/"),
    ("Assessoria Xifra", "Mataró", "xifra@assessoriaxifra.com", "https://assessoriaxifra.com/es/contacto-gestoria-mataro/"),
    ("Gestoria Garcia de la Prada", "Mataró", None, "https://garciadelaprada.com/"),
    ("Maffet & Asociados", "Mataró", None, "https://www.gestoria-contable.es/maffet-y-asociados_204334726-000000001/"),
    ("Asesoria Rubén Chacón", "Mataró", None, "https://www.paginasamarillas.es/f/mataro/asesoria-ruben-chacon_020346789_000000001.html"),
    ("Nougestiluro S.L.", "Mataró", None, "https://empresite.eleconomista.es/NOUGESTILURO.html"),
    ("Gestoria Sm", "Mataró", None, "https://gestoriasm.com/"),
    ("Multigestions Assessorament Integral d'Empreses SLP", "Mataró", None, "https://multigestions.com/"),
]

wb = Workbook()
ws = wb.active
ws.title = "gestorias"
ws.append(["nombre", "empresa", "ciudad", "email", "estado", "fecha_envio", "fuente_email"])

omitidos = 0
for empresa, ciudad, email, fuente in GESTORIAS:
    if email and email in YA_ENVIADOS:
        email, fuente = None, None
        omitidos += 1
    ws.append([f"equip de {empresa}", empresa, ciudad, email or "", "", "", fuente or ""])

wb.save("contactos_catalan_ronda2.xlsx")
print(f"Creado contactos_catalan_ronda2.xlsx con {len(GESTORIAS)} filas ({omitidos} duplicados omitidos).")
