plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/xagri/Documents/GitHub/Agencia de automatizaciones/Agencia-de-automatizaciones"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]