(function () {
  const dictionaries = window.NOESIS_I18N;
  if (!dictionaries) return;

  Object.assign(dictionaries.es, {
    "site.nav.solutions": "Soluciones",
    "site.nav.useCases": "Casos de uso",
    "site.nav.integrations": "Integraciones",
    "site.nav.method": "Proceso",
    "site.nav.results": "Impacto",
    "site.integrations.kicker": "Tecnologías que integramos",
    "site.integrations.homeCta": "Ver integraciones",
    "site.integrations.eyebrow": "Ecosistema tecnológico",
    "site.integrations.title": "Trabajamos con las herramientas que ya usas.",
    "site.integrations.lead": "No imponemos una plataforma. Conectamos tu operativa con la combinación más útil de automatización, IA, datos y canales.",
    "site.integrations.principle1.title": "Tu stack primero",
    "site.integrations.principle1.text": "Revisamos las herramientas que ya utiliza el equipo antes de proponer una nueva.",
    "site.integrations.principle2.title": "Conexiones mantenibles",
    "site.integrations.principle2.text": "Diseñamos flujos documentados, trazables y fáciles de revisar cuando cambia el proceso.",
    "site.integrations.principle3.title": "IA con criterio",
    "site.integrations.principle3.text": "La IA se aplica donde aporta valor; las reglas claras y la revisión humana siguen presentes.",
    "site.integrations.group.ai": "IA y conocimiento",
    "site.integrations.group.automation": "Automatización",
    "site.integrations.group.channels": "Canales y captación",
    "site.integrations.group.data": "Datos y operación",
    "site.integrations.group.business": "Negocio y pagos",
    "site.integrations.group.custom": "Conexiones a medida",
    "site.integrations.ai.api": "IA por API",
    "site.integrations.ai.apiDesc": "Clasificación, extracción y asistentes",
    "site.integrations.ai.knowledge": "Bases de conocimiento",
    "site.integrations.ai.knowledgeDesc": "Documentación y criterios del negocio",
    "site.integrations.automation.n8n": "Flujos y webhooks",
    "site.integrations.automation.make": "Escenarios entre aplicaciones",
    "site.integrations.automation.python": "Procesos y conectores a medida",
    "site.integrations.channels.whatsapp": "Atención y presupuestos",
    "site.integrations.channels.typeform": "Captación estructurada",
    "site.integrations.channels.email": "Email y web",
    "site.integrations.channels.emailDesc": "Formularios, bandejas y avisos",
    "site.integrations.data.google": "Sheets, Drive y Calendar",
    "site.integrations.data.supabase": "Datos, autenticación y portal",
    "site.integrations.data.csv": "Importación y exportación",
    "site.integrations.business.stripe": "Pagos y portal de cliente",
    "site.integrations.business.crm": "Leads, estados y seguimiento",
    "site.integrations.business.erp": "ERP / gestión",
    "site.integrations.business.erpDesc": "Conexión según disponibilidad técnica",
    "site.integrations.custom.api": "Integraciones directas",
    "site.integrations.custom.webhooks": "Eventos en tiempo real",
    "site.integrations.custom.docs": "Documentos",
    "site.integrations.custom.docsDesc": "PDF, imagen y plantillas",
    "site.integrations.custom.title": "¿Tu herramienta no aparece?",
    "site.integrations.custom.text": "Si dispone de API, webhooks, correo o exportación de datos, normalmente podemos conectarla. Lo comprobamos durante el diagnóstico.",
    "site.useCases.eyebrow": "Casos de uso",
    "site.useCases.title": "Así ayudamos según tu necesidad y tu área de trabajo.",
    "site.useCases.lead": "Partimos de un problema operativo concreto y diseñamos un flujo donde automatización y revisión humana trabajan juntas.",
    "site.useCases.problem": "Problema habitual",
    "site.useCases.flow": "Flujo automatizado",
    "site.useCases.review": "Revisión humana",
    "site.useCases.outcome": "Resultado",
    "site.useCases.support.title": "Atención y soporte",
    "site.useCases.support.problem": "Consultas repetidas, respuestas fuera de horario y mensajes dispersos.",
    "site.useCases.support.flow": "El asistente consulta la documentación y responde o clasifica la solicitud.",
    "site.useCases.support.review": "El equipo recibe excepciones, contexto e historial cuando debe intervenir.",
    "site.useCases.support.outcome": "Respuesta más rápida y atención coherente.",
    "site.useCases.admin.title": "Administración y finanzas",
    "site.useCases.admin.problem": "Facturas, adjuntos y datos que se copian manualmente entre sistemas.",
    "site.useCases.admin.flow": "Lectura, extracción, validación y preparación para exportar o registrar.",
    "site.useCases.admin.review": "Se revisan importes, incidencias y documentos que no cumplen las reglas.",
    "site.useCases.admin.outcome": "Menos transcripción y más control documental.",
    "site.useCases.sales.title": "Comercial y ventas",
    "site.useCases.sales.problem": "Leads sin respuesta, seguimientos olvidados y propuestas lentas.",
    "site.useCases.sales.flow": "Captura, clasificación, asignación, recordatorios y propuesta estructurada.",
    "site.useCases.sales.review": "El comercial valida prioridades, personaliza y decide el siguiente paso.",
    "site.useCases.sales.outcome": "Más oportunidades atendidas con orden.",
    "site.useCases.ops.title": "Operaciones",
    "site.useCases.ops.problem": "Tareas repetitivas sin visibilidad y procesos que dependen de memoria.",
    "site.useCases.ops.flow": "Estados, responsables, alertas y comunicaciones internas conectadas.",
    "site.useCases.ops.review": "El equipo gestiona excepciones y decisiones que requieren criterio.",
    "site.useCases.ops.outcome": "Menos retrabajo y una operativa más clara.",
    "site.useCases.booking.title": "Servicios con cita",
    "site.useCases.booking.problem": "Llamadas, cambios de hora y huecos de agenda difíciles de coordinar.",
    "site.useCases.booking.flow": "Reserva, confirmación, recordatorios y sincronización con calendario.",
    "site.useCases.booking.review": "El equipo interviene en cambios especiales o necesidades concretas.",
    "site.useCases.booking.outcome": "Agenda más ordenada y menos interrupciones.",
    "site.useCases.cta.eyebrow": "El siguiente paso",
    "site.useCases.cta.title": "Empecemos por el proceso que más tiempo te roba.",
    "site.home.final.eyebrow": "¿Listo para empezar?",
    "site.home.final.title": "Descubre qué proceso puedes ordenar primero.",
    "site.home.final.text": "Una conversación de 30–45 minutos para entender tu operativa y valorar un piloto concreto.",
    "site.contact.hero.eyebrow": "Diagnóstico operativo",
    "site.contact.hero.title": "Cuéntanos qué proceso te quita tiempo.",
    "site.contact.hero.text": "En una primera conversación revisamos cómo circula la información, dónde se repite trabajo y qué oportunidad tendría sentido probar primero.",
    "site.contact.next.eyebrow": "Qué pasará después",
    "site.contact.next.title": "Una primera revisión clara, sin compromiso.",
    "site.contact.next1.title": "Nos cuentas el proceso",
    "site.contact.next1.text": "Qué ocurre hoy, quién interviene y dónde se acumula el trabajo.",
    "site.contact.next2.title": "Preparamos el diagnóstico",
    "site.contact.next2.text": "Revisamos herramientas, volumen, excepciones y posibles indicadores.",
    "site.contact.next3.title": "Te proponemos el primer paso",
    "site.contact.next3.text": "Si hay encaje, definimos un piloto acotado con alcance y criterios claros.",
    "site.common.viewSolutions": "Ver soluciones",
    "site.common.requestDiagnosis": "Solicitar diagnóstico",
    "site.common.talk": "Hablar de mi proceso",
    "site.footer.explore": "Explorar"
  });

  Object.assign(dictionaries.ca, {
    "site.nav.solutions": "Solucions",
    "site.nav.useCases": "Casos d'ús",
    "site.nav.integrations": "Integracions",
    "site.nav.method": "Procés",
    "site.nav.results": "Impacte",
    "site.integrations.kicker": "Tecnologies que integrem",
    "site.integrations.homeCta": "Veure integracions",
    "site.integrations.eyebrow": "Ecosistema tecnològic",
    "site.integrations.title": "Treballem amb les eines que ja utilitzes.",
    "site.integrations.lead": "No imposem una plataforma. Connectem la teva operativa amb la combinació més útil d'automatització, IA, dades i canals.",
    "site.integrations.principle1.title": "El teu stack primer",
    "site.integrations.principle1.text": "Revisem les eines que ja utilitza l'equip abans de proposar-ne una de nova.",
    "site.integrations.principle2.title": "Connexions mantenibles",
    "site.integrations.principle2.text": "Dissenyem fluxos documentats, traçables i fàcils de revisar quan canvia el procés.",
    "site.integrations.principle3.title": "IA amb criteri",
    "site.integrations.principle3.text": "La IA s'aplica on aporta valor; les regles clares i la revisió humana continuen presents.",
    "site.integrations.group.ai": "IA i coneixement",
    "site.integrations.group.automation": "Automatització",
    "site.integrations.group.channels": "Canals i captació",
    "site.integrations.group.data": "Dades i operació",
    "site.integrations.group.business": "Negoci i pagaments",
    "site.integrations.group.custom": "Connexions a mida",
    "site.integrations.ai.api": "IA per API",
    "site.integrations.ai.apiDesc": "Classificació, extracció i assistents",
    "site.integrations.ai.knowledge": "Bases de coneixement",
    "site.integrations.ai.knowledgeDesc": "Documentació i criteris del negoci",
    "site.integrations.automation.n8n": "Fluxos i webhooks",
    "site.integrations.automation.make": "Escenaris entre aplicacions",
    "site.integrations.automation.python": "Processos i connectors a mida",
    "site.integrations.channels.whatsapp": "Atenció i pressupostos",
    "site.integrations.channels.typeform": "Captació estructurada",
    "site.integrations.channels.email": "Email i web",
    "site.integrations.channels.emailDesc": "Formularis, safates i avisos",
    "site.integrations.data.google": "Sheets, Drive i Calendar",
    "site.integrations.data.supabase": "Dades, autenticació i portal",
    "site.integrations.data.csv": "Importació i exportació",
    "site.integrations.business.stripe": "Pagaments i portal de client",
    "site.integrations.business.crm": "Leads, estats i seguiment",
    "site.integrations.business.erp": "ERP / gestió",
    "site.integrations.business.erpDesc": "Connexió segons disponibilitat tècnica",
    "site.integrations.custom.api": "Integracions directes",
    "site.integrations.custom.webhooks": "Esdeveniments en temps real",
    "site.integrations.custom.docs": "Documents",
    "site.integrations.custom.docsDesc": "PDF, imatge i plantilles",
    "site.integrations.custom.title": "La teva eina no apareix?",
    "site.integrations.custom.text": "Si disposa d'API, webhooks, correu o exportació de dades, normalment la podem connectar. Ho comprovem durant el diagnòstic.",
    "site.useCases.eyebrow": "Casos d'ús",
    "site.useCases.title": "Així ajudem segons la teva necessitat i la teva àrea de treball.",
    "site.useCases.lead": "Partim d'un problema operatiu concret i dissenyem un flux on automatització i revisió humana treballen juntes.",
    "site.useCases.problem": "Problema habitual",
    "site.useCases.flow": "Flux automatitzat",
    "site.useCases.review": "Revisió humana",
    "site.useCases.outcome": "Resultat",
    "site.useCases.support.title": "Atenció i suport",
    "site.useCases.support.problem": "Consultes repetides, respostes fora d'horari i missatges dispersos.",
    "site.useCases.support.flow": "L'assistent consulta la documentació i respon o classifica la sol·licitud.",
    "site.useCases.support.review": "L'equip rep excepcions, context i historial quan ha d'intervenir.",
    "site.useCases.support.outcome": "Resposta més ràpida i atenció coherent.",
    "site.useCases.admin.title": "Administració i finances",
    "site.useCases.admin.problem": "Factures, adjunts i dades que es copien manualment entre sistemes.",
    "site.useCases.admin.flow": "Lectura, extracció, validació i preparació per exportar o registrar.",
    "site.useCases.admin.review": "Es revisen imports, incidències i documents que no compleixen les regles.",
    "site.useCases.admin.outcome": "Menys transcripció i més control documental.",
    "site.useCases.sales.title": "Comercial i vendes",
    "site.useCases.sales.problem": "Leads sense resposta, seguiments oblidats i propostes lentes.",
    "site.useCases.sales.flow": "Captura, classificació, assignació, recordatoris i proposta estructurada.",
    "site.useCases.sales.review": "El comercial valida prioritats, personalitza i decideix el següent pas.",
    "site.useCases.sales.outcome": "Més oportunitats ateses amb ordre.",
    "site.useCases.ops.title": "Operacions",
    "site.useCases.ops.problem": "Tasques repetitives sense visibilitat i processos que depenen de memòria.",
    "site.useCases.ops.flow": "Estats, responsables, alertes i comunicacions internes connectades.",
    "site.useCases.ops.review": "L'equip gestiona excepcions i decisions que requereixen criteri.",
    "site.useCases.ops.outcome": "Menys retraball i una operativa més clara.",
    "site.useCases.booking.title": "Serveis amb cita",
    "site.useCases.booking.problem": "Trucades, canvis d'hora i buits d'agenda difícils de coordinar.",
    "site.useCases.booking.flow": "Reserva, confirmació, recordatoris i sincronització amb calendari.",
    "site.useCases.booking.review": "L'equip intervé en canvis especials o necessitats concretes.",
    "site.useCases.booking.outcome": "Agenda més ordenada i menys interrupcions.",
    "site.useCases.cta.eyebrow": "El següent pas",
    "site.useCases.cta.title": "Comencem pel procés que més temps et roba.",
    "site.home.final.eyebrow": "A punt per començar?",
    "site.home.final.title": "Descobreix quin procés pots ordenar primer.",
    "site.home.final.text": "Una conversa de 30–45 minuts per entendre la teva operativa i valorar un pilot concret.",
    "site.contact.hero.eyebrow": "Diagnòstic operatiu",
    "site.contact.hero.title": "Explica'ns quin procés et pren temps.",
    "site.contact.hero.text": "En una primera conversa revisem com circula la informació, on es repeteix feina i quina oportunitat tindria sentit provar primer.",
    "site.contact.next.eyebrow": "Què passarà després",
    "site.contact.next.title": "Una primera revisió clara, sense compromís.",
    "site.contact.next1.title": "Ens expliques el procés",
    "site.contact.next1.text": "Què passa avui, qui hi intervé i on s'acumula la feina.",
    "site.contact.next2.title": "Preparem el diagnòstic",
    "site.contact.next2.text": "Revisem eines, volum, excepcions i possibles indicadors.",
    "site.contact.next3.title": "Et proposem el primer pas",
    "site.contact.next3.text": "Si hi ha encaix, definim un pilot acotat amb abast i criteris clars.",
    "site.common.viewSolutions": "Veure solucions",
    "site.common.requestDiagnosis": "Sol·licitar diagnòstic",
    "site.common.talk": "Parlar del meu procés",
    "site.footer.explore": "Explorar"
  });
})();
